#!/usr/bin/tcsh -f
echo "************"
#-------------------#

set my_work_dir = 'pwd'

if($#argv != 1) then
  echo "Info: Please provide the csv file"
  exit 1
endif

if(! -f $argv[1]||$argv[1] == "-help") then
    if($argv[1] != "-help") then
        echo "Error: Cannot find csv file $argv[1]. Exiting..."
        exit 1
    else
        echo "Thses are directories"
        echo
        echo "<Design Name> is the name of the top module"
        echo
        echo "<Output Directory> is the name of ouput directory where synthesis timing report is stored"
        echo
        echo "<Netlist Directory> is the name of directory where RTl list is present"
        echo
        echo "<Library Path> is the file path of the cell library to be used for STA"
        echo
        echo "<Constratints file> is the csv file path of constraints to be used for STA"
        exit 1
    endif
else
  exit 1
  #tclsh vsdsynth.tcl $argv[1]
endif

     
